### ISSUE TITLE
cross-platform build?

### ISSUE THREAD

**Issue by psifertex** [rikodot/binja_native_sigscan#1]
I realize this is a huge pain and likely requires us to finish setting up some example action scripts to better support cross-platform building, but it would be great if the plugin supported other platforms besides windows.

Mostly just putting this here to track it since I know someone will want it. 😉

**Comment by rikodot** [comment]
Customized code base to be compilable on linux (using input prompt instead of reading directly from clipboard) and uploaded linux binaries - [related commit](https://github.com/rikodot/binja_native_sigscan/commit/77089be1b7c84f38dfb423a12567753eb8806f5c). Also added better support for dev builds to the loader since dev builds seem to roll out almost on daily basis - [related commit](https://github.com/rikodot/binja_native_plugin_loader/commit/9e847b78c744bf87fd7929a9459878de56636917). And lastly, I discovered a problem causing the loader to crash in some cases when a new version of native binary is released - [fixed here](https://github.com/rikodot/binja_native_plugin_loader/commit/670b6330f04a14213338fb61b04d5545596d47e2). 🙂
