### ISSUE TITLE
Binja 4.0 builds

### ISSUE THREAD

**Issue by apekros** [rikodot/binja_native_sigscan#12]
Would be much appreciated to get the actions to run 4.0 builds for this

**Comment by rikodot** [comment]
If you are on windows, you will need to compile the binaries manually as my BN license is no longer active and actions can't compile windows versions - [build process](https://github.com/rikodot/binja_native_sigscan?tab=readme-ov-file#build-process).

For linux and macos, the binaries have been uploaded to [releases](https://github.com/rikodot/binja_native_sigscan/releases/tag/1.0.4) and once Vector35 updates [their plugin repository](https://github.com/Vector35/community-plugins) with the new changes, all should work.

In case you do not want to wait, you might update the plugin manually:
1. remove the sigscan plugin from binary ninja plugin manager and close binary ninja
2. remove the old binary from plugins folder (`%appdata%\Binary Ninja\plugins\` or `~/.binaryninja/plugins/`)
3. put the new binary into plugins folder and start binary ninja

Thank you for raising this issue as I did not pay attention to the new versions. Since my license is no longer valid, I could not verify functionality of the new binaries. If there are any problems, please reopen this issue.
