### ISSUE TITLE
Installing issue, 20.04.2023

### ISSUE THREAD

**Issue by 701982376509132690** [rikodot/binja_native_sigscan#4]
![изображение](https://user-images.githubusercontent.com/43756332/233198767-7ed5bf26-089b-4279-aa94-3efb46ed2024.png)

**Comment by rikodot** [comment]
As far as I am aware this issue is related to Binary Ninja itself rather than my plugin.
For further information, you can execute the command in cmd to see exactly what is going on `"C:\Program Files\Vector35\BinaryNinja\plugins\python\python.exe" -m pip --isolated --disable-pip-version-check install --verbose --target "C:\Users\<user>\AppData\Roaming\Binary Ninja\python310\site-packages" requests bs4`.
The plugin might still work even if the pip installation fails depending if required packages have been installed in the past.
To fix this manually, what you can do is install required packages using regular python (if you have it installed on your system) rather the one bundled with Binary Ninja by executing `python -m pip --isolated --disable-pip-version-check install --verbose --target "C:\Users\<user>\AppData\Roaming\Binary Ninja\python310\site-packages" requests bs4` in cmd.

**Comment by trodery** [comment]
I can confirm that I just tried this and it worked! Thank you!
