### ISSUE TITLE
sigscan causing binja to crash on startup

### ISSUE THREAD

**Issue by OGApex** [rikodot/binja_native_sigscan#9]
Binary Ninja Version: 3.5.4526 Personal

Windows 11 Version 22H2

The latest version of sigscan from the plugin manager seems to cause binja to crash before it starts up. I have attached the call stack for when this happens.

Call stack:
![Screenshot 2024-01-17 024543](https://github.com/rikodot/binja_native_sigscan/assets/57691390/d1c48180-63e5-4d55-8cfe-882d94239d3d)

**Comment by rikodot** [comment]
This is caused by a workaround I use for compiling the plugin using github actions (happens on windows only). I recompiled it manually on my machine and updated the repository. This fixes the crashing. You might need to head to `%appdata%\Binary Ninja\plugins` and remove the dll manually before starting Binary Ninja again. Thank you.
